name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  scrap:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: actions/github-script@v6
      with:
        script: |
          console.log('this is test message')

