name: Community Scrapper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  scrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm start
